### ISSUE TITLE
protection prayer leads to slower kills

### ISSUE THREAD

**Issue by gmiclotte** [visua0/Melvor-Idle-Combat-Simulator-Reloaded#27]
I notice on rokken, enabling protect ranged results in slower kills over no prayer.
 - Nomeru

**Comment by rolfson32** [comment]
Ran into the same issue and was debugging on my own, I *think* it's related to this line:

https://github.com/visua0/Melvor-Idle-Combat-Simulator-Reloaded/blob/master/Extension/sources/workers/simulator.js#L1715

With protection prayers, it should be:

"actor.accuracy = protectFromValue;"

which sets the accuracy to 15%, rather than the current code that sets protected accuracy to 85% every time, as protectFromValue == 15.

That didn't seem to affect my sims too much when I ran it with the fix in place, but at the very least it did stop having a large drop in kill speed when running protect prayers.

**Comment by gmiclotte** [comment]
Aha, looks like Malcs swapped it around earlier this month...
![2021-03-29_18-01](https://user-images.githubusercontent.com/12995926/112865173-cc3f1300-90b8-11eb-9b14-857319a587a4.png)

Thanks a lot for figuring it out! I'll fix it later this week.

**Comment by rolfson32** [comment]
Sure thing! And I was actually testing locally on an old version of the addon. With the latest version + that fix, things look better as I go from 70.1 kills/hr without protection prayers to 79 kills/hr with prot ranged up.

I think there's still a bug somewhere around accuracy, though. Without any protection prayers up, Rokken has a 40% chance to hit on the combat page but when I run the sim I see "Attacks made/h: 1426 // Attacks Taken/h: 828.4" which is right at 60% chance to hit when he should have 40%. 

With protection prayers that value changes to around 50% chance to hit, so protect is definitely affecting accuracy but it doesn't seem to be set correctly.

**Comment by gmiclotte** [comment]
Attacks made/h is player attacks ("attacks made by player")
Attacks taken/h is enemy attacks ("attacks taken by player")

If you want to see hit rate, you could enable the additional logging in `simulationResult` in `simulator.js`, and then check the console. Note: idk how that handles multi-attacks, I only used it for debugging single hit attacks.

**Comment by rolfson32** [comment]
I checked with other enemies that don't have any special attacks that could be messing with the attacks taken/hr and I'm seeing the same thing. With a naked gear set against a raging horned elite, he has a base hit chance of 56% and no special attacks.

Without protection prayers:

1372 Attacks made/hr
910 Attacks taken/hr

66% accuracy (this should be 56%)

---

With protection prayers:

1373 Attacks made/hr
912 Attacks taken/hr

910 Attacks taken/hr

66% accuracy (this should be 15%) as well. Hrm.

Unfortunately out of time for debugging this for now as I've gotta get back to work but I'll look into this further this afternoon.

**Comment by rolfson32** [comment]
Ok I lied - looking into this a little bit further, those two stats aren't related at all lol.

`        // attacks
        simResult.attacksTakenPerSecond = stats.enemyAttackCalls / totalTime * 1000;
        simResult.attacksMadePerSecond = stats.playerAttackCalls / totalTime * 1000;`
        
Attacks taken per second = enemy attacks, attacks made per second = player attacks. And the # of attacks doesn't change with protection prayers because it's only attack *calls*, not attack *hits*. Checking a better stat like food used per hour or hp lost/hr both update correctly with protection prayers up.

Case solved, just fix that one line and we're back in business :)

**Comment by gmiclotte** [comment]
Should be fixed in today's release (v1.3.8), thanks!
