### ISSUE TITLE
[Suggestion] Track slayer xp when not on task but in a slayer area

### ISSUE THREAD

**Issue by Gnuder** [visua0/Melvor-Idle-Combat-Simulator-Reloaded#66]
As title says I think it would be cool if it could show slayer xp/hr when fighting monsters in a slayer area but not on task.

**Comment by gmiclotte** [comment]
Probably a bug due to the 0.20 to 0.21 rework, it absolutely should show slayer xp/h. Thanks!

**Comment by gmiclotte** [comment]
Should be fixed in v1.5.12

The way the additional slayer xp from being in a slayer area is computed was changed in Melvor v0.21?1111 and I didn't think to reflect that change in the sim. Thanks for the report!

I even wrote the bug report that eventually resulted in that change in the game lol, my bad :upside_down_face:
